const List<String> categoriasKeys = [
  'playas',
  'islas_y_islotes',
  'reservas',
  'cascadas',
  'lagunas',
  'termas',
  'balnearios_y_complejos',
  'volcanes',
  'cuevas_y_cavernas',
  'deportes_extremos',
  'telefericos_y_tarabitas',
  'sitios_arqueologicos',
  'iglesias',
  'museos',
  'centros_culturales',
  'monumentos_y_plazas',
  'pueblos_magicos',
  'fincas_y_haciendas',
  'parques',
  'miradores',
  'parques_tematicos_y_diversiones',
  'restaurantes',
  'cafeterias_y_bares',
  'vida_nocturna',
];

const Map<String, String> categoriaLabels = {
  'playas': 'Playas',
  'islas_y_islotes': 'Islas y Islotes',
  'reservas': 'Reservas',
  'cascadas': 'Cascadas',
  'lagunas': 'Lagunas',
  'termas': 'Termas',
  'balnearios_y_complejos': 'Balnearios y Complejos',
  'volcanes': 'Volcanes',
  'cuevas_y_cavernas': 'Cuevas y Cavernas',
  'deportes_extremos': 'Deportes Extremos',
  'telefericos_y_tarabitas': 'Teleféricos y Tarabitas',
  'sitios_arqueologicos': 'Sitios Arqueológicos',
  'iglesias': 'Iglesias',
  'museos': 'Museos',
  'centros_culturales': 'Centros Culturales',
  'monumentos_y_plazas': 'Monumentos y Plazas',
  'pueblos_magicos': 'Pueblos Mágicos',
  'fincas_y_haciendas': 'Fincas y Haciendas',
  'parques': 'Parques',
  'miradores': 'Miradores',
  'parques_tematicos_y_diversiones': 'Parques Temáticos y Diversiones',
  'restaurantes': 'Restaurantes',
  'cafeterias_y_bares': 'Cafeterías y Bares',
  'vida_nocturna': 'Vida Nocturna',
};
